import './globals.css';

import { Geist } from 'next/font/google';
import localFont from 'next/font/local';
import { TRPCReactProvider } from '@/trpc';
import {
	HydrationErrorBoundary,
	HydrationFix,
	StickingProvider,
	ThemeProvider,
} from '@/components/providers';
import type { Metadata } from 'next';
import type { ReactNode } from 'react';

export const metadata: Metadata = {
	title: 'RandoDrum',
	description: 'Generated by create-t3-app',
	icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const geist = Geist({
	subsets: ['latin'],
	variable: '--font-geist-sans',
});

const musisync = localFont({
	src: '../../public/Musisync.ttf',
	variable: '--font-musisync',
	display: 'swap',
});

export default function RootLayout({
	children,
}: Readonly<{ children: ReactNode }>) {
	return (
		<html lang='en' className={`${geist.variable} ${musisync.variable}`}>
			<body>
				<HydrationFix />
				<HydrationErrorBoundary>
					<ThemeProvider>
						<StickingProvider>
							<TRPCReactProvider>{children}</TRPCReactProvider>
						</StickingProvider>
					</ThemeProvider>
				</HydrationErrorBoundary>
			</body>
		</html>
	);
}
